general:
  environment: residential
  input_dir: data/
  output_dir: data/output
  cmap: data/cmap_kitti.npy

preprocessing:
  img_mean: [0.485, 0.456, 0.406]
  img_std: [0.229, 0.224, 0.225]

model:
  num_classes: 6
  device: cuda
  weights: data/weights/hydranet.ckpt
  encoder_config:  [[1, 16, 1, 1], # expansion rate, output channels, number of repeats, stride
                        [6, 24, 2, 2],
                        [6, 32, 3, 2],
                        [6, 64, 4, 2],
                        [6, 96, 3, 1],
                        [6, 160, 3, 2],
                        [6, 320, 1, 1],
                        ]
  

