general:
  environment: safetrip
  input_dir: ../data/
  output_dir: ../output/
  cmap: ../data/cmap_safetrip_24.npy

preprocessing:
  img_mean: [0.485, 0.456, 0.406]
  img_std: [0.229, 0.224, 0.225]

model:
  num_classes: 24  # 6 Surface + 18 Polygon classes (filtered)
  device: cuda
  weights: null  # Train from scratch, or specify path to pretrained weights
  encoder_config:  [[1, 16, 1, 1], # expansion rate, output channels, number of repeats, stride
                        [6, 24, 2, 2],
                        [6, 32, 3, 2],
                        [6, 64, 4, 2],
                        [6, 96, 3, 1],
                        [6, 160, 3, 2],
                        [6, 320, 1, 1],
                        ]

training:
  batch_size: 8
  learning_rate: 0.001
  weight_decay: 0.0001
  epochs: 100
  optimizer: AdamW
  scheduler: cosine
  warmup_epochs: 5
  
  # Loss weights
  lambda_seg: 0.5  # Initial segmentation weight
  lambda_depth: 0.5  # Initial depth weight
  
  # Dynamic loss balancing
  use_uncertainty_weighting: true
  
  # Data settings
  train_split: 0.8
  num_workers: 4
  
  # Augmentation
  augment: true
  
  # Checkpointing
  save_freq: 5  # Save every N epochs
  checkpoint_dir: ../checkpoints/safetrip/
  
  # Logging
  log_freq: 10  # Log every N iterations
  tensorboard_dir: ../logs/safetrip/

evaluation:
  # Segmentation metrics
  seg_metrics: ['mIoU', 'pixel_accuracy', 'class_accuracy']
  
  # Depth metrics
  depth_metrics: ['rmse', 'mae', 'abs_rel', 'delta_1.25']
  
  # Evaluation settings
  eval_batch_size: 16
  save_predictions: true
  prediction_dir: ../predictions/safetrip/

dataset:
  name: SafeTrip-Q
  root: ../data/
  img_size: [512, 512]  # Height, Width
  
  # Class information
  class_weights_path: ../data/class_weights_24.npy
  class_info_path: ../data/class_info.json
  
  # Depth settings
  max_depth: 100.0  # Maximum depth in meters
  min_depth: 0.1    # Minimum valid depth
  
  # KITTI integration
  use_kitti: true   # Whether to use KITTI depth data
  kitti_ratio: 0.4  # Ratio of KITTI samples in each batch (40%)
  
inference:
  # Inference settings
  input_size: [512, 512]
  output_stride: 1  # Full resolution output
  flip_test: false  # Test-time augmentation
  
  # Visualization
  save_viz: true
  viz_dir: ../visualizations/safetrip/
  alpha: 0.5  # Overlay transparency