general:
  environment: safetrip
  input_dir: ../data/
  output_dir: ../output/
  cmap: ../data/cmap_safetrip_24.npy

preprocessing:
  img_mean: [0.485, 0.456, 0.406]
  img_std: [0.229, 0.224, 0.225]

model:
  name: segformer
  encoder: mit_b2
  num_classes: 24
  pretrained: cityscapes
  device: cuda

dataset:
  root: ../data/
  img_size: [512, 512]
  class_info_path: ../data/class_info.json
  class_weights_path: ../data/class_weights_24.npy

training:
  batch_size: 8
  learning_rate: 0.0001
  weight_decay: 0.01
  epochs: 20
  optimizer: AdamW
  scheduler: polynomial
  
  # Data settings
  train_split: 0.8
  num_workers: 4
  
  # Augmentation
  augment: true
  
  # Checkpointing
  save_freq: 5
  checkpoint_dir: ../checkpoints/teacher/

evaluation:
  eval_batch_size: 4
  save_predictions: true
  output_dir: ../output/teacher/